# Generated by Django 4.0.3 on 2022-04-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_beginning_of_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
